# -*- mode: ruby -*-
# vi: set ft=ruby :

ENV['VAGRANT_NO_PARALLEL'] = 'yes'

Vagrant.configure(2) do |config|

  config.vm.provision "shell", path: "bootstrap.sh"

  NodeCount = 2

  (1..NodeCount).each do |i|
    config.vm.define "ubuntuvm0#{i}" do |node|
      node.vm.box = "bento/ubuntu-20.04"
      node.vm.hostname = "ubuntuvm0#{i}.b0x.it"
      node.vm.network "public_network", bridge: "wlp0s20f3"
#, ip: "192.168.102.7#{i}"
      node.vm.provider "virtualbox" do |v|
        v.name = "ubuntu-204-b0x-0#{i}"
        v.memory = 2048
        v.cpus = 1
      end
    end
  end

end
