# -*- mode: ruby -*-
# vi: set ft=ruby :
ENV['VAGRANT_NO_PARALLEL'] = 'yes'

Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-20.04"
  config.ssh.insert_key = false
  config.vm.network "public_network", bridge: "wlp0s20f3" # change wlp0s20f3 to your network interface
  config.vm.hostname = "ubuntuvm01"
  config.vm.provision "shell", path: "bootstrap.sh"
  config.vm.synced_folder '.', '/vagrant'

  # General VirtualBox VM configuration.
  config.vm.provider :virtualbox do |v|
    v.memory = 2048
    v.cpus = 1
    v.linked_clone = true
    
    v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
    v.customize ["modifyvm", :id, "--ioapic", "on"]
  end
end